channel_targets:
  - tudat-team dev
channel_sources:
  - tudat-team/label/dev, tudat-team, conda-forge, defaults
boost_cpp:
  - 1.85.0
c_compiler:
  - clang
c_compiler_version:
  - 18
cxx_compiler:
  - clangxx
cxx_compiler_version:
  - 18
