channel_targets:
  - tudat-team main
channel_sources:
  - tudat-team, conda-forge, defaults
boost_cpp:
  - 1.84.0
c_compiler:
  - clang
c_compiler_version:
  - 18
cxx_compiler:
  - clangxx
cxx_compiler_version:
  - 18
