{% set name = "tudat" %}
  {% set version = "2.13.0.dev55" %}
  {% set build = "0" %}
  {% set git_rev = "v" + version %} # git_rev must point to the version tag. Hardcoded version can be replaced by assigning it using the version variable.This also solves formatting and indenantion issues while using the bumpversion command.


package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/tudat-team/tudat.git
  git_rev: {{ git_rev }}

build:
    # A non-negative integer representing the build number of the package.
    #  Unlike the build string, the build_number is inspected by conda.
    #  Conda uses it to sort packages that have otherwise identical names
    #  and versions to determine the latest one. This is important because
    #  new builds that contain bug fixes for the way a package is built may be
    #  added to a repository.
    number: {{ build }}

requirements:
  build:
    # Tools required to build the package. These packages are run on the build
    # system and include things such as revision control systems (Git, SVN) make
    # tools (GNU make, Autotool, CMake) and compilers (real cross, pseudo-cross,
    # or native when not cross-compiling), and any source pre-processors.
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make                     # [unix]
outputs:
  - name: {{ name }}
    requirements:
      host:
        # Packages that need to be specific to the target platform when the
        # target platform is not necessarily the same as the native build
        # platform
        - tudat-resources
        - boost-cpp {{ boost_cpp }}
        - cspice-cmake
        - sofa-cmake
        - nlohmann_json
        - eigen
        - nrlmsise-00
      run:
        # Packages required to run the package. These are the dependencies
        # that are installed automatically whenever the package is installed.
        # Package names should follow the package match specifications.
        - {{ pin_compatible('libcurl', max_pin='x.x') }}
        - {{ pin_compatible('boost-cpp', max_pin='x.x') }}
        - {{ pin_compatible('tudat-resources', max_pin='x.x') }}
        - {{ pin_compatible('cspice-cmake', max_pin='x.x') }}
        - {{ pin_compatible('sofa-cmake', max_pin='x.x') }}
        - {{ pin_compatible('nrlmsise-00', max_pin='x.x') }}
    test:
      downstreams:
        - tudatpy
        - tudatpy-base

about:
  home: https://docs.tudat.space/
  license: BSD
  license_family: BSD
  summary: A C++ platform to perform astrodynamics and space research.

extra:
  recipe-maintainers:
    - geoffreygarrett
    - DominicDirkx
